# Blog
keywords: Damao,ZhengJing,UX,UI,大猫的设计本
author: 郑静,zheng_927@163.com
description: Nothing lasts forever.
avatar: /images/favicon.png

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: 
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
